#!/bin/bash

# ИНСТРУКЦИИ ПО ВОССТАНОВЛЕНИЮ HTTPS COLOR360.RU
echo "🔒 ВОССТАНОВЛЕНИЕ HTTPS ДЛЯ COLOR360.RU"
echo "======================================="

echo ""
echo "🎯 ПРОБЛЕМА ОПРЕДЕЛЕНА:"
echo "======================"
echo "❌ Сайт ранее был доступен через https://color360.ru/"
echo "❌ Сейчас работает только http://color360.ru/"
echo "❌ Панорама https://color360.ru/pano/ недоступна"
echo "❌ Редактор изображений не работает без HTTPS"

echo ""
echo "💡 ПРИЧИНА:"
echo "==========="
echo "Отсутствует или неправильно настроен SSL сертификат"
echo "Nginx не сконфигурирован для HTTPS"
echo "Нет редиректов с HTTP на HTTPS"

echo ""
echo "🚀 РЕШЕНИЯ (выберите подходящий вариант):"
echo "========================================="

echo ""
echo "🟢 ВАРИАНТ 1: ПОЛНАЯ НАСТРОЙКА HTTPS (рекомендуется)"
echo "===================================================="
echo "Время: 5-10 минут"
echo "Что делает: Устанавливает SSL сертификат с нуля"
echo ""
echo "wget https://raw.githubusercontent.com/RadaRish/color360/main/setup-https-complete.sh"
echo "chmod +x setup-https-complete.sh"
echo "sudo bash setup-https-complete.sh"
echo ""
echo "Включает:"
echo "✅ Установку Certbot"
echo "✅ Получение Let's Encrypt сертификата"
echo "✅ Настройку nginx для HTTPS"
echo "✅ Автоматические редиректы HTTP → HTTPS"
echo "✅ Заголовки безопасности"
echo "✅ Автообновление сертификатов"
echo "✅ HTTP/2 поддержку"

echo ""
echo "🟡 ВАРИАНТ 2: БЫСТРОЕ ИСПРАВЛЕНИЕ"
echo "================================="
echo "Время: 1-2 минуты"  
echo "Что делает: Использует существующий сертификат"
echo ""
echo "wget https://raw.githubusercontent.com/RadaRish/color360/main/fix-https-quick.sh"
echo "chmod +x fix-https-quick.sh"
echo "sudo bash fix-https-quick.sh"
echo ""
echo "Подходит если:"
echo "✓ SSL сертификат уже установлен"
echo "✓ Нужно только исправить nginx конфигурацию"

echo ""
echo "🔍 ВАРИАНТ 3: ДИАГНОСТИКА ПРОБЛЕМ"
echo "================================="
echo "Время: 1 минута"
echo "Что делает: Анализирует текущее состояние HTTPS"
echo ""
echo "wget https://raw.githubusercontent.com/RadaRish/color360/main/diagnose-https.sh"
echo "chmod +x diagnose-https.sh" 
echo "sudo bash diagnose-https.sh"
echo ""
echo "Показывает:"
echo "🔍 Состояние SSL сертификатов"
echo "🔍 Доступность доменов"
echo "🔍 Конфигурацию nginx"
echo "🔍 Результаты HTTP/HTTPS тестов"

echo ""
echo "📋 ПОШАГОВЫЙ ПЛАН ВОССТАНОВЛЕНИЯ:"
echo "================================="

echo ""
echo "ШАГ 1: Диагностика текущего состояния"
echo "-------------------------------------"
echo "sudo bash diagnose-https.sh"
echo ""
echo "Это покажет:"
echo "- Есть ли SSL сертификат"
echo "- Работает ли nginx"
echo "- Доступны ли домены"

echo ""
echo "ШАГ 2А: Если сертификат ЕСТЬ"
echo "----------------------------"
echo "sudo bash fix-https-quick.sh"
echo ""
echo "Быстро настроит HTTPS с существующим сертификатом"

echo ""
echo "ШАГ 2Б: Если сертификата НЕТ"
echo "----------------------------"
echo "sudo bash setup-https-complete.sh"
echo ""
echo "Полная установка HTTPS с получением нового сертификата"

echo ""
echo "ШАГ 3: Проверка результата"
echo "-------------------------"
echo "Откройте в браузере:"
echo "- https://color360.ru/"
echo "- https://color360.ru/pano/"
echo ""
echo "Должно работать без ошибок SSL"

echo ""
echo "🛠️ РУЧНАЯ ДИАГНОСТИКА (если автоскрипты не помогают):"
echo "====================================================="

echo ""
echo "1. Проверка nginx:"
echo "   sudo systemctl status nginx"
echo "   sudo nginx -t"

echo ""
echo "2. Проверка сертификатов:"
echo "   sudo certbot certificates"
echo "   sudo ls -la /etc/letsencrypt/live/color360.ru/"

echo ""
echo "3. Проверка портов:"
echo "   sudo netstat -tuln | grep -E ':80|:443'"
echo "   sudo ufw status"

echo ""
echo "4. Тест SSL подключения:"
echo "   openssl s_client -connect color360.ru:443 -servername color360.ru"

echo ""
echo "5. Проверка доступности:"
echo "   curl -I http://color360.ru/"
echo "   curl -I https://color360.ru/"

echo ""
echo "🚨 КРИТИЧЕСКИЕ ПРОБЛЕМЫ И РЕШЕНИЯ:"
echo "=================================="

echo ""
echo "❌ ПРОБЛЕМА: 'Connection refused' на порт 443"
echo "РЕШЕНИЕ:"
echo "   sudo ufw allow 443/tcp"
echo "   sudo systemctl restart nginx"

echo ""
echo "❌ ПРОБЛЕМА: 'SSL certificate problem'"
echo "РЕШЕНИЕ:"
echo "   sudo certbot renew --force-renewal"
echo "   sudo systemctl reload nginx"

echo ""
echo "❌ ПРОБЛЕМА: 'nginx: configuration file test failed'"
echo "РЕШЕНИЕ:"
echo "   sudo nginx -t  # посмотреть ошибку"
echo "   sudo bash fix-https-quick.sh  # пересоздать конфиг"

echo ""
echo "❌ ПРОБЛЕМА: DNS не резолвится"
echo "РЕШЕНИЕ:"
echo "   Проверить настройки домена у регистратора"
echo "   Убедиться что A-запись указывает на IP сервера"

echo ""
echo "🎯 ОЖИДАЕМЫЙ РЕЗУЛЬТАТ ПОСЛЕ ВОССТАНОВЛЕНИЯ:"
echo "==========================================="

echo ""
echo "✅ https://color360.ru/ - главная страница загружается по HTTPS"
echo "✅ https://color360.ru/pano/ - панорамный просмотр работает"
echo "✅ http://color360.ru/ автоматически перенаправляется на HTTPS"
echo "✅ В браузере показывается зеленый замок (валидный SSL)"
echo "✅ Редактор изображений с LaMa API работает через HTTPS"
echo "✅ Нет предупреждений о смешанном содержимом"

echo ""
echo "🔧 ПОСЛЕ УСПЕШНОЙ НАСТРОЙКИ:"
echo "============================"

echo ""
echo "📱 Обновите закладки и ссылки:"
echo "   http://color360.ru/ → https://color360.ru/"
echo "   http://color360.ru/pano/ → https://color360.ru/pano/"

echo ""
echo "🔄 Настройте автообновление:"
echo "   Сертификаты обновляются автоматически каждые 12 часов"
echo "   Лог обновлений: tail -f /var/log/certbot-renew.log"

echo ""
echo "🛡️ Проверьте безопасность:"
echo "   Все HTTP запросы перенаправляются на HTTPS"
echo "   Установлены заголовки безопасности"
echo "   Поддерживается HTTP/2"

echo ""
echo "📊 МОНИТОРИНГ HTTPS:"
echo "==================="

echo ""
echo "Регулярные проверки:"
echo "- curl -I https://color360.ru/"
echo "- sudo certbot certificates"
echo "- sudo systemctl status nginx"
echo "- tail -f /var/log/nginx/color360_error.log"

echo ""
echo "⏰ ВРЕМЯ ВЫПОЛНЕНИЯ:"
echo "==================="
echo "- Диагностика: 30 секунд - 1 минута"
echo "- Быстрое исправление: 1-2 минуты"  
echo "- Полная настройка: 5-10 минут"
echo "- DNS обновление (если нужно): до 24 часов"

echo ""
echo "🎉 После выполнения вы получите полнофункциональный"
echo "   HTTPS сайт с современной защитой и автообновлением!"