#!/bin/bash

# ИНСТРУКЦИИ ПО ВОССТАНОВЛЕНИЮ НЕДОСТУПНОГО САЙТА
echo "🚨 САЙТ color360.ru НЕДОСТУПЕН - ПЛАН ВОССТАНОВЛЕНИЯ"
echo "=================================================="

echo ""
echo "📋 СИТУАЦИЯ:"
echo "- Сайт https://color360.ru/ недоступен"
echo "- Панорама https://color360.ru/pano/ недоступна" 
echo "- Возможные причины: nginx, файлы сайта, конфигурация"

echo ""
echo "⚡ БЫСТРОЕ ВОССТАНОВЛЕНИЕ (выберите один из вариантов):"
echo "======================================================"

echo ""
echo "🔴 ВАРИАНТ 1: МГНОВЕННОЕ ВОССТАНОВЛЕНИЕ (30 сек)"
echo "wget https://raw.githubusercontent.com/RadaRish/color360/main/emergency-restore.sh"
echo "chmod +x emergency-restore.sh"
echo "sudo bash emergency-restore.sh"
echo ""
echo "Что делает: Создает минимальный рабочий сайт с временными страницами"

echo ""
echo "🟡 ВАРИАНТ 2: ПОЛНАЯ ДИАГНОСТИКА И АВТОИСПРАВЛЕНИЕ (2-3 мин)"  
echo "wget https://raw.githubusercontent.com/RadaRish/color360/main/emergency-site-restore.sh"
echo "chmod +x emergency-site-restore.sh"
echo "sudo bash emergency-site-restore.sh"
echo ""
echo "Что делает: Полная диагностика и автоматическое исправление всех проблем"

echo ""
echo "🟢 ВАРИАНТ 3: ВОССТАНОВЛЕНИЕ ИЗ РЕПОЗИТОРИЯ (1-2 мин)"
echo "wget https://raw.githubusercontent.com/RadaRish/color360/main/restore-from-github.sh"
echo "chmod +x restore-from-github.sh" 
echo "sudo bash restore-from-github.sh"
echo ""
echo "Что делает: Загружает свежие файлы из GitHub и полностью восстанавливает сайт"

echo ""
echo "🔵 КОМПЛЕКСНОЕ ВОССТАНОВЛЕНИЕ (рекомендуется):"
echo "=============================================="
echo "# 1. Быстрое восстановление доступности"
echo "wget -O emergency-restore.sh https://raw.githubusercontent.com/RadaRish/color360/main/emergency-restore.sh"
echo "sudo bash emergency-restore.sh"
echo ""
echo "# 2. Полное восстановление файлов"  
echo "wget -O restore-from-github.sh https://raw.githubusercontent.com/RadaRish/color360/main/restore-from-github.sh"
echo "sudo bash restore-from-github.sh"
echo ""
echo "# 3. Финальная диагностика"
echo "wget -O emergency-site-restore.sh https://raw.githubusercontent.com/RadaRish/color360/main/emergency-site-restore.sh"
echo "sudo bash emergency-site-restore.sh"

echo ""
echo "🛠️ РУЧНАЯ ДИАГНОСТИКА (если автоматические скрипты не помогли):"
echo "=============================================================="

echo ""
echo "1. 🔍 Проверка nginx:"
echo "   sudo systemctl status nginx"
echo "   sudo nginx -t"
echo "   sudo systemctl restart nginx"

echo ""  
echo "2. 📁 Проверка файлов сайта:"
echo "   ls -la /var/www/html/"
echo "   ls -la /var/www/color360/"
echo "   ls -la /var/www/html/pano/"

echo ""
echo "3. 🌐 Проверка доступности:"
echo "   curl -I http://localhost/"
echo "   curl -I http://localhost/pano/"
echo "   curl -I http://color360.ru/"

echo ""
echo "4. 📋 Проверка логов:"
echo "   sudo tail -f /var/log/nginx/error.log"
echo "   sudo tail -f /var/log/nginx/access.log"
echo "   sudo journalctl -u nginx -f"

echo ""
echo "5. 🔧 Проверка портов и процессов:"
echo "   sudo netstat -tuln | grep :80"
echo "   sudo ps aux | grep nginx"
echo "   sudo lsof -i :80"

echo ""
echo "🆘 КРИТИЧЕСКАЯ СИТУАЦИЯ (если ничего не помогает):"
echo "============================================="

echo ""
echo "1. 🔄 Полная перезагрузка nginx:"
echo "   sudo systemctl stop nginx"
echo "   sudo pkill -f nginx"
echo "   sudo systemctl start nginx"

echo ""
echo "2. 🔥 Сброс конфигурации nginx:"
echo "   sudo rm -f /etc/nginx/sites-enabled/*"
echo "   sudo nginx -s reload"
echo "   # Затем запустите emergency-restore.sh"

echo ""
echo "3. 🛡️ Проверка файрвола:"
echo "   sudo ufw status"
echo "   sudo ufw allow 80/tcp"
echo "   sudo ufw allow 443/tcp"

echo ""
echo "4. 💻 Перезагрузка сервера:"
echo "   sudo reboot"

echo ""
echo "📞 ТЕХПОДДЕРЖКА:"
echo "=============="
echo "Если проблема не решается автоматически:"
echo ""
echo "1. 📸 Сделайте скриншоты ошибок"
echo "2. 📋 Сохраните логи:"
echo "   sudo journalctl -u nginx --since '1 hour ago' > nginx_logs.txt"
echo "   sudo tail -100 /var/log/nginx/error.log > nginx_errors.txt"
echo "3. 🔍 Запустите диагностику:"
echo "   sudo bash emergency-site-restore.sh > diagnosis.txt 2>&1"

echo ""
echo "🎯 ОЖИДАЕМЫЙ РЕЗУЛЬТАТ ПОСЛЕ ВОССТАНОВЛЕНИЯ:"
echo "=========================================="
echo "✅ http://color360.ru/ - главная страница доступна"
echo "✅ http://color360.ru/pano/ - панорамный просмотр работает"  
echo "✅ Все статические файлы (CSS, JS, изображения) загружаются"
echo "✅ Нет ошибок 404, 403, 500 в браузере"
echo "✅ Логи nginx не показывают критических ошибок"

echo ""
echo "⏱️ ВРЕМЯ ВОССТАНОВЛЕНИЯ:"
echo "======================"
echo "- Экстренное восстановление: 30 секунд - 1 минута"
echo "- Полное восстановление: 2-5 минут"
echo "- DNS обновление (если нужно): до 24 часов"

echo ""
echo "🎉 После успешного восстановления можно проверить:"
echo "- Работу ретуши LaMa: bash lama-monitor.sh"
echo "- Статус всех сервисов: bash fix-all-issues.sh"
echo "- Мониторинг системы: bash lama-monitor.sh monitor"